name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Show workspace
        run: |
          node -v
          npm -v
          npx next --version || true
          ls -la
          echo "package.json scripts:" && cat package.json | jq '.scripts'

      - name: Install
        run: npm ci --no-audit --no-fund

      - name: Build (capture full logs)
        run: |
          set -o pipefail
          npm run build --silent 2>&1 | tee build.log

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
